name: Convert MKV to HLS and Deploy

on:
  repository_dispatch:
    types: [convert-video]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Set timestamp for preview folder
      id: vars
      run: echo "ts=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Download MKV video
      run: |
        mkdir -p input
        curl -L "${{ github.event.client_payload.video_url }}" -o input/input.mkv

    - name: Convert first 1 minute to HLS
      run: |
        mkdir -p public/hls/preview-${{ steps.vars.outputs.ts }}
        ffmpeg -ss 0 -t 60 -i input/input.mkv \
          -preset veryfast \
          -profile:v main \
          -start_number 0 \
          -hls_time 5 \
          -hls_list_size 0 \
          -f hls public/hls/preview-${{ steps.vars.outputs.ts }}/preview.m3u8

    - name: Keep only latest 5 previews
      run: |
        cd public/hls
        ls -1dt preview-* | tail -n +6 | xargs rm -rf || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
