name: Convert MKV to HLS and Deploy

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "Raw MKV file URL"
        required: true
      timestamp:
        description: "Timestamp (used to create folder)"
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Create input and output directories
      run: |
        mkdir -p input
        mkdir -p public/hls/preview-${{ github.event.inputs.timestamp }}

    - name: Download MKV video
      run: |
        echo "Downloading video..."
        curl -L "${{ github.event.inputs.video_url }}" -o input/input.mkv

    - name: Convert first 60 seconds to HLS format
      run: |
        ffmpeg -ss 0 -t 10 -i input/input.mkv \
          -vf "format=yuv420p" \
          -c:v libx264 -preset veryfast -profile:v high \
          -c:a aac \
          -start_number 0 \
          -hls_time 5 \
          -hls_list_size 0 \
          -f hls public/hls/preview-${{ github.event.inputs.timestamp }}/preview.m3u8

    - name: Clean up older previews (keep latest 5)
      run: |
        cd public/hls
        ls -1dt preview-* | tail -n +6 | xargs rm -rf || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
