name: Multiply (Inline Python)

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "First number"
        required: true
        type: string
      num2:
        description: "Second number"
        required: true
        type: string

jobs:
  multiply:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Multiply numbers using inline Python
        run: |
          python -c 'num1 = float("${{ inputs.num1 }}"); num2 = float("${{ inputs.num2 }}"); result = num1 * num2; print("Result:", result)'
