name: Multiply Numbers

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "First number"
        required: true
        type: string
      num2:
        description: "Second number"
        required: true
        type: string

jobs:
  multiply:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Multiply and save result to JSON
        run: |
          echo "import json" > multiply.py
          echo "num1 = float('${{ inputs.num1 }}')" >> multiply.py
          echo "num2 = float('${{ inputs.num2 }}')" >> multiply.py
          echo "result = num1 * num2" >> multiply.py
          echo "print(f'Result: {result}')" >> multiply.py
          echo "with open('result.json', 'w') as f: json.dump({'result': result}, f)" >> multiply.py
          python multiply.py

      - name: Upload result JSON
        uses: actions/upload-artifact@v3.1.3
        with:
          name: result
          path: result.json
